export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_SUCCESS';
export const LIKE_ARTICLE_ERROR = 'LIKE_ARTICLE_ERROR';
export const DISLIKE_ARTICLE_SUCCESS = 'DISLIKE_ARTICLE_SUCCESS';
export const DISLIKE_ARTICLE_ERROR = 'DISLIKE_ARTICLE_ERROR';
export const GET_LIKES = 'GET_LIKES';
export const LIKE_ARTICLE_REQUEST = 'LIKE_ARTICLE_REQUEST';
export const DISLIKE_ARTICLE_REQUEST = 'DISLIKE_ARTICLE_REQUEST';