export const PROFILE_FOLLOW_DATA = 'PROFILE_FOLLOW_DATA';
export const PROFILE_FOLLOW_DATA_SUCCESS = 'PROFILE_FOLLOW_DATA_SUCCESS';
export const PROFILE_FOLLOW_ERROR = 'PROFILE_FOLLOW_ERROR';

export const PROFILE_FOLLOWERS_START = 'PROFILE_FOLLOWERS_START';
export const PROFILE_FOLLOWERS_ERROR = 'PROFILE_FOLLOWERS_ERROR';
export const PROFILE_FOLLOWERS_SUCCESS = 'PROFILE_FOLLOWERS_SUCCESS';

export const PROFILE_FOLLOWING_START = 'PROFILE_FOLLOWING_START';
export const PROFILE_FOLLOWING_ERROR = 'PROFILE_FOLLOWING_ERROR';
export const PROFILE_FOLLOWING_SUCCESS = 'PROFILE_FOLLOWING_SUCCESS';

export const PROFILE_FOLLOW_POST_START = 'PROFILE_FOLLOW_POST_START';
export const PROFILE_FOLLOW_POST_ERROR = 'PPROFILE_FOLLOW_POST_ERROR';
export const PROFILE_FOLLOW_POST_SUCCESS = 'PROFILE_FOLLOW_POST_SUCCESS';

export const PROFILE_FOLLOW_USER_ERROR = 'PROFILE_FOLLOW_USER_ERROR';
export const PROFILE_FOLLOW_USER_SUCCESS = 'PROFILE_FOLLOW_USER_SUCCESS';
export const PROFILE_FOLLOW_USER_START = 'PROFILE_FOLLOW_USER_START';

export const USER_UNFOLLOW_START = 'USER_UNFOLLOW_START';
export const USER_UNFOLLOW_SUCCESS = 'USER_UNFOLLOW_SUCCESS';
export const USER_UNFOLLOW_ERROR = 'USER_UNFOLLOW_ERROR';
