export const ARTICLE_FETCH = 'ARTICLE_FETCH';
export const ARTICLE_FETCH_SUCCESS = 'ARTICLE_FETCH_SUCCESS';
export const ARTICLE_FETCH_ERROR = 'ARTICLE_FETCH_ERROR';
export const CLEAR = 'CLEAR';
export const ARTICLE_POST = 'ARTICLE_POST';
export const ARTICLE_POST_ERROR = 'ARTICLE_POST_ERROR';
export const ARTICLE_POST_SUCCESS = 'ARTICLE_POST_SUCCESS';
