export const FACEBOOK = 'FACEBOOK_AUTH_CODE';
export const GOOGLE = 'GOOGLE_AUTH_CODE';
export const TWITTER = 'TWITTER_AUTH_CODE';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_ERROR = 'SOCIAL_LOGIN_ERROR';
export const SOCIAL_LOGIN_START = 'SOCIAL_LOGIN_START';
